name: test
on: 
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - scripts/**
      - src/**
      - test/**

jobs:
  generate:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Build pywinrt.exe
        run: ./scripts/vsdevcmd-build.cmd
      - name: generate
        working-directory: projection
        run: ./generate.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: generated
          path: |
            projection/cppwinrt/
            projection/pywinrt/
  test:
    runs-on: windows-2022
    needs: generate
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', "3.11"]
        architecture: ['x86', 'x64']
        release-type: ['Release'] # no "Debug" - https://github.com/actions/setup-python/issues/86
    name: Python ${{ matrix.python-version }} ${{ matrix.architecture }} ${{ matrix.release-type }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: generated
          path: projection/
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: build
        run: |
          Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" -DevCmdArguments '-arch=${{ matrix.architecture }}'
          cd projection
          ./build.ps1 -buildType ${{ matrix.release-type }} -pythonVersion ${{ matrix.python-version }}
        shell: powershell
      - name: Run tests
        env:
          PYTHONPATH: projection/pywinrt
        run: python -m unittest -v
  lint:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Build pywinrt
        run: ./scripts/vsdevcmd-build.cmd
      - name: Generate full projection
        run: |
          cd projection
          ./generate -fullProjection
      - name: Run mypy
        run: |
          cd projection
          pipx run mypy -p winrt
